class CreateClientAuthclients < ActiveRecord::Migration

  #this migration is generated by client_auth gem

  def change

    create_table :client_auth_clients do |t|
      t.string :key, null: false # device id
      t.string :token, null: false
      t.references :owner, polymorphic: true
      t.text :details, default: "{}", null: false
      t.string :status, null: false, default: 'active'

      t.timestamps
    end

    add_index :client_auth_clients, :key, unique: true
    add_index :client_auth_clients, :token, unique: true
    add_index :client_auth_clients, :user_id
    add_index :client_auth_clients, :status
    

  end

end
